"""
Django settings for contrataciones project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
import os
import environ
from datetime import (
    timedelta,
)  # <--- IMPORTANTE: Necesario para configurar el tiempo del token

# 1. PRIMERO definimos BASE_DIR
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Inicializamos la librería environ
env = environ.Env()

# 3. Leemos el archivo .env
environ.Env.read_env(BASE_DIR / ".env")

# --- CONFIGURACIÓN SEGURA ---
SECRET_KEY = env("SECRET_KEY")
DEBUG = env.bool("DEBUG", default=False)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Render inyecta esta variable automáticamente con el hostname del servicio
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Parche para que Playwright funcione (solo si estamos en modo DEBUG)
if DEBUG:
    os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",  # Optimización estáticos
    "django.contrib.staticfiles",
    "corsheaders",  # <--- OBLIGATORIO: Para conectar con Vercel
    "django_q",  # <--- Cola de tareas (Emails, PDFs)
    "contratos",  # <--- Tu app principal
    "ninja",
    "ninja_extra",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",  # <--- Para invalidar tokens en logout
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # <--- Archivos estáticos en Render
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # <--- OBLIGATORIO: Debe ir AL PRINCIPIO
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "contrataciones.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "contrataciones.wsgi.application"


# Database
# Lee la URL de conexión desde el archivo .env (Render la inyecta automáticamente)
DATABASES = {
    "default": env.db(),
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# Motor de almacenamiento eficiente para producción (WhiteNoise)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- CONFIGURACIÓN DE CORS (OPCIÓN 1: PUERTAS ABIERTAS) ---
# Esto permite que Vercel (y cualquier otro) se conecte sin problemas.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# --- CONFIGURACIÓN DE DJANGO-Q (Cola de Tareas) ---
Q_CLUSTER = {
    "name": "contrataciones",
    "workers": 4,
    "recycle": 500,
    "timeout": 60,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "cpu_affinity": 1,
    "label": "Django Q",
    "orm": "default",
}

# --- CONFIGURACIÓN DE JWT (Tokens) ---
# Esto define cuánto dura la sesión de tu compañero
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),  # <--- ¡Dura 1 día entero!
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),  # <--- Refresh dura 1 semana
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "contratos.auth_rules.user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("ninja_jwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "ninja_jwt.models.TokenUser",
    "JTI_CLAIM": "jti",
}

# --- CONFIGURACIÓN DE EMAIL (RESEND) ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.resend.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "resend"  # Siempre es 'resend'
EMAIL_HOST_PASSWORD = env(
    "RESEND_API_KEY", default="dummy-key-para-tests"
)  # Lee la key del .env
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="onboarding@resend.dev")
