"""
Django settings for contrataciones project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
import os
import environ

# 1. PRIMERO definimos BASE_DIR (para saber la ruta del proyecto)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Inicializamos la librería environ
env = environ.Env()

# 3. AHORA SÍ leemos el archivo .env usando BASE_DIR
# (Nota: Quitamos los paréntesis extra que causaban error)
environ.Env.read_env(BASE_DIR / ".env")

# --- CONFIGURACIÓN SEGURA ---
SECRET_KEY = env("SECRET_KEY")
DEBUG = env.bool("DEBUG", default=False)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Parche para que Playwright funcione (solo si estamos en modo DEBUG)
if DEBUG:
    os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",  # <--- Optimización para estáticos en dev
    "django.contrib.staticfiles",
    "corsheaders",  # <--- Para permitir conexión con Frontend (React, etc)
    "django_q",  # <--- El motor de tareas
    "contratos",  # <--- Tu nueva app
    'ninja',
    'ninja_extra',  # <--- NUEVO
    'ninja_jwt',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # <--- Sirve archivos estáticos en Docker
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # <--- Permite peticiones del exterior
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "contrataciones.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "contrataciones.wsgi.application"


# Database
# Lee la URL de conexión desde el archivo .env
DATABASES = {
    "default": env.db(),
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = (
    BASE_DIR / "staticfiles"
)  # <--- Carpeta donde se recolectarán los estáticos
# Motor de almacenamiento eficiente para producción
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- CONFIGURACIÓN DE CORS (Frontend) ---
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])

# --- CONFIGURACIÓN DE DJANGO-Q (Cola de Tareas) ---
Q_CLUSTER = {
    "name": "contrataciones",
    "workers": 4,
    "recycle": 500,
    "timeout": 60,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "cpu_affinity": 1,
    "label": "Django Q",
    "orm": "default",
}
