# Generated by Django 5.2.10 on 2026-01-29 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("nombre_organo_entidad", models.CharField(max_length=255)),
                ("nombre_unidad_revisora", models.CharField(max_length=255)),
                (
                    "nomenclatura",
                    models.CharField(max_length=100, verbose_name="Código Documento"),
                ),
                ("fecha_revision", models.DateField()),
                (
                    "persona_contacto",
                    models.CharField(max_length=255, verbose_name="Elaborado Por"),
                ),
                ("nombre_completo_revisor", models.CharField(max_length=255)),
                (
                    "caaue1_incluye_actividades_previas",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue2_incluye_acta_inicio",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue3_incluye_pliego_condiciones",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue4_publicacion_llamado_snc",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue5_publicacion_llamado_ente",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue6_incluye_registro_adquirientes",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue7_incluye_modificaciones",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue8_incluye_acta_recepcion_sobres",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue9_incluye_acta_apertura_sobres",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue10_incluye_ofertas",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue11_incluye_garantias_sostenimiento",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue12_incluye_certificado_rnc",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue13_incluye_certificado_snc",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue14_incluye_solvencias",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue15_incluye_informe_recomendacion",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue16_incluye_adjudicacion",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue17_incluye_notificacion",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue18_incluye_garantias_contratacion",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue19_incluye_contrato_u_orden",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue20_incluye_resp_social",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue21_identificacion_nomenclatura",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue22_expediente_foliado",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue23_identificacion_tomos",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "caaue24_archivo_custodia",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO"), ("NA", "NO APLICA")],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "usuario_revisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualConfiguracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_institucion_ente", models.CharField(max_length=255)),
                ("siglas_institucion_ente", models.CharField(max_length=50)),
                ("nombre_unidad_admin_financiera", models.CharField(max_length=255)),
                ("nombre_unidad_sistemas_tecnologia", models.CharField(max_length=255)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cargo",
                    models.CharField(max_length=150, verbose_name="Cargo del Usuario"),
                ),
                (
                    "nombre_institucion_ente",
                    models.CharField(max_length=255, verbose_name="Institución"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_registro", models.DateField(auto_now_add=True)),
                ("correo_proveedor", models.EmailField(max_length=254)),
                (
                    "nombre_proveedor",
                    models.CharField(max_length=255, verbose_name="Razón Social"),
                ),
                ("rif_proveedor", models.CharField(max_length=20, verbose_name="RIF")),
                (
                    "tipo_persona",
                    models.CharField(
                        choices=[("N", "Natural"), ("J", "Jurídica")], max_length=1
                    ),
                ),
                (
                    "tipo_entidad_juridica",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("estado", models.CharField(max_length=100)),
                ("municipio", models.CharField(max_length=100)),
                ("parroquia", models.CharField(max_length=100)),
                ("direccion_fiscal", models.TextField()),
                ("telefono_proveedor", models.CharField(max_length=20)),
                ("nombre_rep_legal", models.CharField(max_length=255)),
                ("cedula_rep_legal", models.CharField(max_length=20)),
                ("tiene_rnc", models.BooleanField(default=False)),
                ("tiene_solvencia_laboral", models.BooleanField(default=False)),
                ("tiene_licencia_municipal", models.BooleanField(default=False)),
                ("actividad_comercial_principal", models.BooleanField(default=False)),
                (
                    "area_especialidad",
                    models.CharField(
                        choices=[
                            ("Bienes", "Bienes"),
                            ("Obras", "Obras"),
                            ("Servicio", "Servicio"),
                        ],
                        max_length=50,
                    ),
                ),
                ("anos_experiencia", models.PositiveIntegerField(default=0)),
                ("fecha_estado_financiero", models.DateField(blank=True, null=True)),
                (
                    "patrimonio_reportado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "nivel_contratacion",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Media"),
                            ("BAJA", "Baja"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
