# Generated by Django 5.1.4 on 2026-04-27 18:36

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_admin_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    if not User.objects.filter(email="universitasdev@gmail.com").exists():
        User.objects.create(
            username="universitasdev@gmail.com",
            email="universitasdev@gmail.com",
            password=make_password("universitas123"),
            is_staff=True,
            is_superuser=True,
            is_active=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("contratos", "0001_initial"),
        ("auth", "__first__"),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
