# Generated by Django 5.1.4 on 2026-03-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contratos", "0002_codigoresetpassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualconfiguracion",
            name="correo_electronico_manual",
            field=models.EmailField(
                default="", max_length=50, verbose_name="Correo destino del manual"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="actividad_comercial_principal",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
