# Generated by Django 5.1.4 on 2026-04-27 18:49

from django.db import migrations


def force_admin_permissions(apps, schema_editor):
    User = apps.get_model("auth", "User")
    # Buscar el usuario y forzar permisos de administrador
    try:
        user = User.objects.get(email="universitasdev@gmail.com")
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("contratos", "0002_create_admin"),
    ]

    operations = [
        migrations.RunPython(force_admin_permissions),
    ]
