# Generated by Django 5.1.4 on 2026-03-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contratos", "0003_manualconfiguracion_correo_electronico_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
